bcc: null
cc: null
enabled: true
language: orderLanguage
name: 'Bestellung TV Website an bestellung@terra-verde.ch'
plainTextTemplatePath: ''
recipientType: custom
replyTo: null
subject: 'Bestellung Website – {{order.user.fullName}} – Nr.{{order.reference }} – {{ order.shippingMethodName }}'
templatePath: /shop/_email/order-confirmation-tv.twig
to: bestellung@terra-verde.ch
