descriptionFormat: ''
handle: clothing
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: false
name: Clothing
productFieldLayouts:
  e409dd29-0075-4315-8e13-29d2ed37e770:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
productTitleFormat: ''
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147:
    hasUrls: true
    template: shop/products/_product
    uriFormat: 'shop/products/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
