descriptionFormat: ''
handle: delicatesses
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: Delikatessen
productFieldLayouts:
  e409dd29-0075-4315-8e13-29d2ed37e770:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
          -
            fieldUid: 944f60e0-b559-4698-bb4d-3d2eec04eef6 # Produkt Beschreibung Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d59a8a70-d5e0-42b4-b4d8-d3602f3bbe03 # Produkt Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Produktinformationen
        sortOrder: 1
productTitleFormat: ''
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147:
    hasUrls: true
    template: shop/_product
    uriFormat: 'shop/delikatessen/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
variantFieldLayouts:
  10b1ec85-975d-4ee9-8745-929e8bf3d448:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
