descriptionFormat: ''
handle: whitewine
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: Weissweine
productFieldLayouts:
  c448d189-4a78-4de1-870d-aebd2f1e3808:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
          -
            fieldUid: 944f60e0-b559-4698-bb4d-3d2eec04eef6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d59a8a70-d5e0-42b4-b4d8-d3602f3bbe03
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Produktinformationen
        sortOrder: 1
      -
        elements:
          -
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            warning: null
        name: Varianten
        sortOrder: 2
productTitleFormat: ''
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147:
    hasUrls: true
    template: shop/_product
    uriFormat: 'shop/weissweine/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
variantFieldLayouts:
  6738957a-64b8-4beb-ae63-60f7719443d0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
