field: 944f60e0-b559-4698-bb4d-3d2eec04eef6
fieldLayouts:
  e3f955f3-9132-4c35-a529-4f0b143b945b:
    tabs:
      -
        elements:
          -
            fieldUid: 52b07f6a-0a03-4f36-90a6-237e75e980b9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  52b07f6a-0a03-4f36-90a6-237e75e980b9:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: descriptionCopy
name: Beschreibung
sortOrder: 1
