field: a48a5f48-ae99-438a-94f7-9574fe7fbf92 # Inhaltselemente
fieldLayouts:
  da16f83a-bb42-4035-820a-356ff0438eed:
    tabs:
      -
        elements:
          -
            fieldUid: 06be1401-4934-4dfa-9342-a78552156b4e # Textfeld hinzufügen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e7fec16d-a352-4a94-8ec1-8e902b366c3b # Textfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b696c979-d69e-481e-9fe6-248daa5b218a # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  06be1401-4934-4dfa-9342-a78552156b4e: # Textfeld hinzufügen
    columnSuffix: qbyqnxla
    contentColumnType: text
    fieldGroup: null
    handle: textFieldNewsletter
    instructions: ''
    name: 'Textfeld hinzufügen'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Newsletter.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b696c979-d69e-481e-9fe6-248daa5b218a: # Hintergrundfarbe
    columnSuffix: gnpnfqaf
    contentColumnType: string(7)
    fieldGroup: null
    handle: bgColTextNewsletter
    instructions: 'Grundeinstellung: weiss'
    name: Hintergrundfarbe
    searchable: false
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  e7fec16d-a352-4a94-8ec1-8e902b366c3b: # Textfarbe
    columnSuffix: ovuejipy
    contentColumnType: string(7)
    fieldGroup: null
    handle: colorTextNewsletter
    instructions: 'Grundeinstellung: schwarz'
    name: Textfarbe
    searchable: false
    settings:
      defaultColor: '#000000'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
handle: textFieldNewsletter
name: Textfeld
sortOrder: 3
