field: 4c920e95-c071-49d6-974d-175f3cc51bc9 # Youtube Video Liste
fieldLayouts:
  75e2856a-eb98-4e32-be59-eac1c2888175:
    tabs:
      -
        elements:
          -
            fieldUid: 84e9acf3-3abc-4c6e-9375-3a7093c1a3d6 # Youtube Video Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  84e9acf3-3abc-4c6e-9375-3a7093c1a3d6: # Youtube Video Source
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: youtubeVideoSource
    instructions: 'Auf Youtube gehen und Video öffnen. Unterhalb Video auf "Teilen" klicken und im Dialog oben "Einbetten" wählen. Die "src" aus dem Code-Beispiel kopieren (z.B. https://www.youtube.com/embed/oTPf_vweGs0) und hier einfügen.'
    name: 'Youtube Video Source'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: videoItem
name: Video
sortOrder: 1
