fieldLayouts:
  4135bc96-d016-467d-b943-534c528c6c3e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 3b68c41e-26c2-4609-86c4-780ba745ca0e # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: aboutUsStructureDetailPage
hasTitleField: true
name: Detailseite
section: 85ecf639-70f3-47d4-8ad7-c2996049794d # Über uns
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
