fieldLayouts:
  548a5fb1-37d8-4ce5-a046-e00477071922:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4b642df7-00a9-4661-a1c1-68465a3a555a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b205d303-121a-4aae-8c85-bb00a76f312a # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38f8a839-2c0d-48d0-97fd-3b9b3de63d6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c375bd1-b36e-4bbd-a334-ded70ef87b25
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: cf0041a3-d754-42f2-ace8-06993d60bfd8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 838ede95-b646-4f5e-88a9-a41698817481 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f0c3613-5621-42ff-ab8a-a4a6047268fd
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8f56985a-2fb4-4995-91df-59d506564fd6
        userCondition: null
handle: aboutUsStructureOverviewPage
hasTitleField: true
name: Übersichtsseite
section: 85ecf639-70f3-47d4-8ad7-c2996049794d # Über uns
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
