fieldLayouts:
  e1652b46-6834-4179-a2db-2990aa61003f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f936ce6-e8ad-4506-8776-a09b0c87c702
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f37fcdc-93d5-4c04-b953-3e9d86fbaade
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 722653a4-d9c5-4b6b-ad77-ed175bb1db59
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 838ede95-b646-4f5e-88a9-a41698817481 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58f25de2-be5e-41ad-9f64-75f64001a9e1
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8a4dd01f-c394-4b81-8680-f853e13d9119
        userCondition: null
handle: impressum
hasTitleField: true
name: Impressum
section: 6d38f976-5e94-4016-abac-a9e2da77ab07 # Impressum
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
