fieldLayouts:
  811b887b-2b76-40d9-8be1-76895282a48f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: newStructure
hasTitleField: true
name: Neues
section: 9547c4b2-034f-4e07-9a02-b94d052fec7c
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
