fieldLayouts:
  22543e78-0719-48a0-9465-8f72d5890080:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: prdoucersChannel
hasTitleField: true
name: Produzenten
section: 8e2bbb53-7b2a-493f-9592-4847ec7d1194
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
