fieldLayouts:
  185f106b-8825-4c67-b053-8f617bb1e2b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ac40a2b8-cc58-4a24-ad5e-068910f9a136
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff8c13b8-0279-418f-b814-76707004907b
        userCondition: null
handle: producersType
hasTitleField: true
name: 'Produzenten Typ'
section: d4ae6c44-536a-458d-92da-645295622dd6 # Produzenten Typ
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
