fieldLayouts:
  c448b5a5-8e33-4bf2-bdeb-6ff6b83a4747:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1c9b1275-03a3-4fcd-bec4-034e84d1b437 # Kategorien Blog
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1cd651ff-a41f-4d1c-9296-41e714505e6b # Rezepte
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: recipeBlog
hasTitleField: true
name: Rezepte
section: 9547c4b2-034f-4e07-9a02-b94d052fec7c # Blog-Einträge
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
