fieldLayouts:
  fcc9b405-e972-4f63-b942-48d95e2076af:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: registrateSingle
hasTitleField: false
name: Registrieren
section: ea3d0d8a-06a4-48ed-b8aa-3e7cbaa24971 # Registrieren
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
