fieldLayouts:
  dd4a3125-5fe1-4684-89d9-13242b8c3347:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: a6deb9a0-e67c-4fba-bc55-fcba596d4822
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 072ea0f1-6edc-4617-a088-60b1c99374ba # Karten Vorschaubild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Inhalt
        sortOrder: 1
handle: sellingPointsStructure
hasTitleField: true
name: Verkaufsstellen
section: 34eecfa5-9662-4a5c-addd-6a484fbebe8d # Verkaufsstellen Orte
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
