fieldLayouts:
  166912f5-580f-4cf2-8743-e603d4fd387f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: shopStructure
hasTitleField: true
name: Shop
section: 48548b44-1daa-40e6-8a33-e8f7fd5a9bb6
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
