fieldLayouts:
  f8d6fd93-05f3-4184-9b52-0f484eaa5f9a:
    tabs:
      -
        elements:
          -
            fieldUid: dd105ceb-4213-4f13-875f-6f606b9927c2 # Titel
            instructions: ''
            label: 'Überschrift im Newsletter'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: af6dbdfc-a694-4baf-9682-4991b9c728aa # Kopf-Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 10561167-3a73-493b-8f0f-48ce104e8c50 # Anrede verwenden
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b035fa13-d443-491b-9682-b97c664aa7a3 # Anrede
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a936e12c-9de8-4357-940a-6e95e373f08c # Einstiegstext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 81fa4d93-70d8-41a1-b50f-cac685f28201 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 32cd07ee-add2-4f02-8691-39b96171693c # Textfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a48a5f48-ae99-438a-94f7-9574fe7fbf92 # Inhaltselemente
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Campaign
        sortOrder: 1
handle: newsletter
htmlTemplate: email/newsletter.html
name: Newsletter
plaintextTemplate: email/newsletter.html
queryStringParameters: ''
siteUid: dd0cd05e-0cb9-4a76-b993-3cb70e6fc147 # Terra Verde
testContactIds: ''
uriFormat: '{slug}'
