defaultPlacement: beginning
fieldLayouts:
  5ef64903-88e7-46e1-b18a-46956de1a178:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: catGroupForBlog
name: Blog
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    hasUrls: true
    template: _pages/blog/
    uriFormat: 'blog/{slug}'
structure:
  maxLevels: null
  uid: e6efca77-16a4-496f-b985-2db06550a140
