defaultPlacement: end
fieldLayouts:
  6dbec0c4-35ea-4656-ae7c-eafe74079878:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: catGroupDeli
name: Delikatessen
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    hasUrls: true
    template: null
    uriFormat: 'delikatessen/{slug}'
structure:
  maxLevels: null
  uid: b1febd17-a4bf-4e8e-ad97-976a52147212
