defaultPlacement: end
fieldLayouts:
  69d61a75-aa20-4b72-9b37-0380c20ff373:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: catGroupGiftDegu
name: 'Geschenke & Degustationen'
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    hasUrls: true
    template: null
    uriFormat: 'geschenke-degustationen/{slug}'
structure:
  maxLevels: null
  uid: efdc2b71-cd34-449b-9044-9d5b52d8d77b
