defaultPlacement: end
fieldLayouts:
  aae17cea-ebbe-47b2-996c-e2a022a69f42:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: regionsManufactors
name: Regionen
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    hasUrls: true
    template: null
    uriFormat: 'regionen/{slug}'
structure:
  maxLevels: null
  uid: 0a032a6f-9f66-4c5b-9a3b-b3e5e4ab11f1
