childBlocks:
  - titleH2
  - titleH3
  - titleH4
  - formattedText
  - buttonLinkInternal
  - externalLink
  - linkDownload
  - image
  - youtubeVideo
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  3a4f3a17-e648-4926-ada4-4762a0cd8e8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 54175d52-141f-426e-9de0-3891627e7502 # Akkordeon Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83110e70-f563-4356-81bf-4b81020997d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a91450b5-15a1-4780-96c1-0dffea095613 # Akkordeon Zustand
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d669cd7b-8ba5-4cdf-83b6-6ea5fad2e5de
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 3cc1d2d3-6cfd-4058-9b72-d47d2869f58a
        userCondition: null
group: 3c5824e6-9e4f-47c8-b1d2-9d1000064cdf # Aufklappelemente
groupChildBlockTypes: true
handle: accordionPanel
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: AkkordeonPanel
sortOrder: 22
topLevel: false
