childBlocks:
  - titleH2
  - titleH3
  - titleH4
  - formattedText
  - buttonLinkInternal
  - externalLink
  - linkDownload
  - image
  - youtubeVideo
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  3a4f3a17-e648-4926-ada4-4762a0cd8e8d:
    tabs:
      -
        elements:
          -
            fieldUid: 54175d52-141f-426e-9de0-3891627e7502 # Akkordeon Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a91450b5-15a1-4780-96c1-0dffea095613 # Akkordeon Zustand
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
group: 3c5824e6-9e4f-47c8-b1d2-9d1000064cdf # Aufklappelemente
handle: accordionPanel
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: AkkordeonPanel
sortOrder: 21
topLevel: false
