childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
handle: externerLinkPreview
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Externer Link Preview'
sortOrder: 10
topLevel: true
