childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  b2342c7a-acfc-4c2e-87fc-bd0bd2722f8e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cbf7f593-68bf-4c83-b97d-b6959558cb3e # Titel H3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a489088-8d05-4d23-8f8a-31a8583423b0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d22d8183-8d37-4569-9fda-4480d52e3498 # Text Standard ohne Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63ac4c02-f200-4cf5-976c-f40010f0772f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09a21ad7-26ab-46e9-b0d7-84b8d95c3c2d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f836488e-b5ab-4d7d-8b93-f9d9fb95263f # Bild Alt-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d631719e-5c6e-4eb0-8733-f310aefb5367
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 79922ac9-edbc-44e9-850c-3995f6bcdbee # Bild Legende
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df5e9010-7ec8-48e8-863a-8d0d1926179b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 85483609-8f7b-443b-b987-df65cc35c06f # Bild Positionierung
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06bcd08d-c438-44c3-8917-d331f63ef9ec
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 5d2899bd-9de4-4b51-998f-71f3636b3ab3
        userCondition: null
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
groupChildBlockTypes: true
handle: imageText3070
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Bild / Text - 30% / 70%'
sortOrder: 17
topLevel: true
