childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  67b7a086-081b-49f0-8d16-68fd274d0de9:
    tabs:
      -
        elements:
          -
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f836488e-b5ab-4d7d-8b93-f9d9fb95263f # Bild Alt-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 79922ac9-edbc-44e9-850c-3995f6bcdbee # Bild Legende
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: cbf7f593-68bf-4c83-b97d-b6959558cb3e # Titel H3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d22d8183-8d37-4569-9fda-4480d52e3498 # Text Standard ohne Titel
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
handle: imageText5050
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Bild / Text - 50% / 50%'
sortOrder: 16
topLevel: true
