childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  99d585cd-d509-4cc1-9a84-736754107e29:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea4fa903-2dbe-4f3d-a858-25ef0266eba9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79922ac9-edbc-44e9-850c-3995f6bcdbee # Bild Legende
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43c8b58f-be2f-49fa-bde4-f2875491cbcf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f836488e-b5ab-4d7d-8b93-f9d9fb95263f # Bild Alt-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 877c705c-5ce7-4c15-9b1d-eff3249ddd05
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: 6f154b76-c0de-4be0-9dfb-875b9aadfe82
        userCondition: null
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
groupChildBlockTypes: true
handle: imageWide
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Bild Breit'
sortOrder: 13
topLevel: true
