childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  cee308b0-8238-4075-9171-e7ca25136182:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21549f68-7d3d-4435-9ae4-ef64337348a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79922ac9-edbc-44e9-850c-3995f6bcdbee # Bild Legende
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 253edee2-5f65-4fc7-9f0d-2ee4b773c3fe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f836488e-b5ab-4d7d-8b93-f9d9fb95263f # Bild Alt-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 952b1676-5359-4836-9de3-8c7753b75a69
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: bfe24797-aae9-45ef-8599-73ef82183248
        userCondition: null
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
groupChildBlockTypes: true
handle: image
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Bild
sortOrder: 12
topLevel: true
