childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  e77d383a-0b1d-4139-a3fd-8a993ea4f9ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cbf7f593-68bf-4c83-b97d-b6959558cb3e # Titel H3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 253e9eba-d7fe-4ffe-aaa6-bef7b9725cc1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d22d8183-8d37-4569-9fda-4480d52e3498 # Text Standard ohne Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ff55afb-9971-4396-a2d7-ea634f103143
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad566b2c-3536-4ea7-bd18-d84931d8db8a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f836488e-b5ab-4d7d-8b93-f9d9fb95263f # Bild Alt-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba07884a-e521-45c9-b687-4b4245cc1c92
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 79922ac9-edbc-44e9-850c-3995f6bcdbee # Bild Legende
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e61b49e2-9025-4bf9-bce5-51befdc88051
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 32255436-9130-46f8-89a7-da7a18284166 # Box Positionierung
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 421dc51b-eace-4dd2-8016-3f34bfad4506
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 51d5398a-9cc0-4781-bacb-713a68986d17 # Box Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d45826f8-cc5d-49c9-a0e3-cdc193b14f73
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 685ad3f3-ef40-45d9-8934-ec8c2926422f # Box Textfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ee9383e-82b7-4d87-87e0-a4734e7fdec8
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: bf086412-4b0b-4f25-9752-b3a8e7a40c3b
        userCondition: null
group: d87ae540-a64c-4e54-ac23-844cb4371d36 # 
groupChildBlockTypes: true
handle: infobox
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Infobox
sortOrder: 24
topLevel: true
