childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  e77d383a-0b1d-4139-a3fd-8a993ea4f9ee:
    tabs:
      -
        elements:
          -
            fieldUid: cbf7f593-68bf-4c83-b97d-b6959558cb3e # Titel H3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d22d8183-8d37-4569-9fda-4480d52e3498 # Text Standard ohne Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 32255436-9130-46f8-89a7-da7a18284166 # Infobox Positionierung
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 51d5398a-9cc0-4781-bacb-713a68986d17 # Infobox Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 685ad3f3-ef40-45d9-8934-ec8c2926422f # Infobox Textfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Inhalt
        sortOrder: 1
group: d87ae540-a64c-4e54-ac23-844cb4371d36 # 
handle: infobox
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Infobox
sortOrder: 24
topLevel: true
