childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  7b294e65-6e5f-446f-9153-1297a4332462:
    tabs:
      -
        elements:
          -
            fieldUid: 4c920e95-c071-49d6-974d-175f3cc51bc9 # Youtube Video Liste
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
handle: mediaList
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Youtube Video Liste'
sortOrder: 14
topLevel: true
