childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  7b294e65-6e5f-446f-9153-1297a4332462:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4c920e95-c071-49d6-974d-175f3cc51bc9 # Youtube Video Liste
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4c722cf-c510-4ba9-b656-4a0021d23b9b
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 9024c328-6631-4cc3-88cf-45261320ccf9
        userCondition: null
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
groupChildBlockTypes: true
handle: mediaList
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Youtube Video Liste'
sortOrder: 16
topLevel: true
