childBlocks: null
field: e45ebe2d-560e-4f8b-9bc9-6bda46de1a4f # Inhaltselemente Startseite
fieldLayouts:
  af939d49-c4c8-4220-a1c0-d277a243c066:
    tabs:
      -
        elements:
          -
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b19c563f-f580-49f7-88f1-896078bcca7a # Titel H2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86c08488-49e8-48fc-8daf-61b59aaf31fa # Button Link auf Eintrag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 15e8e382-ef35-4ba0-b82a-fd65b047ea1e # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 11b21e6e-604f-4b62-9b9c-63220ad03729 # Link Farbe (simple Button)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
group: null
handle: quicklinkItem
maxBlocks: 0
maxChildBlocks: 3
maxSiblingBlocks: 0
name: Quicklink
sortOrder: 2
topLevel: false
