childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  95b45947-7f32-497f-81ea-f14d807ec2da:
    tabs:
      -
        elements:
          -
            fieldUid: f171c298-b09b-4b12-8d5a-f876e71109f3 # Titel H4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
group: c9e74448-323c-4314-8339-8767051c39f5 # Titel, Text & Links
handle: titleH4
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Titel H4'
sortOrder: 4
topLevel: true
