childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  3b068269-918e-4203-a73d-dcde7f126fc1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cbf7f593-68bf-4c83-b97d-b6959558cb3e # Titel H3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf57440e-4b2f-49eb-9f8b-dd709a04c1f4
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: dee6c7c3-c64c-44dd-9a5b-f54ec6757197
        userCondition: null
group: c9e74448-323c-4314-8339-8767051c39f5 # Titel, Text & Links
groupChildBlockTypes: true
handle: titleH3
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Titel H3'
sortOrder: 3
topLevel: true
