childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  24f61f1c-b1ed-4b2b-903a-0d552ac097e6:
    tabs:
      -
        elements:
          -
            fieldUid: b19c563f-f580-49f7-88f1-896078bcca7a # Titel H2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: titleH2
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Titel H2'
sortOrder: 2
topLevel: true
