childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  ea595a44-4e0e-46c6-9a45-763f351ded50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d05fe0a7-d34a-429f-8f5b-4005eba39588 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 549096b7-5eb7-4653-9fe3-25f70975ae51
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d5c34deb-1091-4df8-86a5-9328eacef81e
        userCondition: null
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
groupChildBlockTypes: true
handle: video
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Video
sortOrder: 14
topLevel: true
