childBlocks: null
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  ea595a44-4e0e-46c6-9a45-763f351ded50:
    tabs:
      -
        elements:
          -
            fieldUid: d05fe0a7-d34a-429f-8f5b-4005eba39588 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
handle: video
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Video
sortOrder: 13
topLevel: true
