childBlocks: null
conditions: null
description: ''
enabled: true
field: 9f46731d-7fdd-4245-9ca1-719db0672448 # Inhaltselemente
fieldLayouts:
  3e094b04-b6d0-42aa-91a9-5459f65e9569:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b42c27d-7e98-4101-b0bd-4f1dacb84869 # Youtube Video Src
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df3af217-8e0d-430c-bf4f-0a4c0b7fbb5c
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 7b923e80-4726-408b-88aa-793c52e32879
        userCondition: null
group: 911777fe-811a-46e9-bb80-0228ddd66234 # Medien
groupChildBlockTypes: true
handle: youtubeVideo
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Youtube Video'
sortOrder: 15
topLevel: true
