tabs:
  -
    elementCondition: null
    elements:
      -
        attribute: addresses
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\users\AddressesField
        uid: 1a5cadc4-1d98-47a6-8244-8c402db5387f
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 1baab5b6-ddf1-4a49-8435-b3bd6a0cc383 # Anrede
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 82f0e9de-a75a-48fb-9df7-6fa7f939a439
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: 982a8eec-f2e3-4260-b25a-904d904b42a9 # Firma
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 45a2de5f-d659-4fe2-82b8-657966996803
        userCondition: null
        warning: null
        width: 25
      -
        elementCondition: null
        fieldUid: 273d5a0c-4e06-47ec-8a4b-c1fcffa5684d # Mindestbestellwert (betrifft nur Detailhandel) - Privat ist Mindestbestellwert generell deaktiviert.
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 47c60c4f-3fd0-44f1-9c80-1348932f9075
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: ada66c36-aa65-4328-b07e-d15f78f13aca # Fax
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4487dd51-b2c3-440e-8677-229383fe61be
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: c280f1d1-4f12-4055-8607-8006585970fd # Telefon
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 53d5ae08-da4a-4670-a330-6a603bf5cd4a
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 3e664364-e972-44e5-9819-78e6cf9ba210 # Telefon (Mobile)
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: dcdf7fdf-6c9b-461f-8151-e05f937a7b7a
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 942ff559-0290-4738-ae31-bd8570484d25 # Adresse
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 9c17e8c2-38a3-4fcf-b8f9-c053c3b73cf4
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: fdcda0cf-8d3c-45eb-ae6f-6a586a0b8d57 # Zusatz Adresse
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 9ce24d26-31dc-4d43-9a8d-2e399c10dc19
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: be930c36-7ffe-488b-b6c5-783c77c32830 # Stadt
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 3ba1a64f-8a58-4e63-8fff-687006ca9b50
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: dbadaaf2-9348-4069-9d8d-3e8e37e3d775 # Postleitzahl
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4be36213-2816-4486-85bd-ac6b7a80ef8c
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: a43c6629-df33-4fa2-a5ca-e073c8ca5841 # Mitteilung
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f75420de-d7a8-405b-9a74-1be9e2c8e354
        userCondition: null
        warning: null
        width: 50
    name: 'Adressen / Einstellungen'
    uid: 0f19432b-3506-49bb-a210-b85f91e1a01c
    userCondition: null
