fieldLayouts:
  1d221156-f409-4f72-91b8-5cb19f1e7c4d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: c8246e09-6dc5-4d7c-91e5-e4ad36778317 # OptimizedImages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: contentImages
hasUrls: true
name: Inhaltsbilder
settings:
  cdnUrlPattern: ''
  customSubfolder: /assets/images/content/content/
  makeUploadsPublic: true
  optimisePrefix: ''
  optimiseUrlPattern: ''
  projectSlug: ''
  securityKey: ''
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: servd\AssetStorage\Volume
url: 'https://cdn2.assets-servd.host/'
