fieldLayouts:
  8f4de9ee-3a11-43d3-b452-7332a0722a1e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
fs: documents
handle: documents
hasUrls: true
name: 'Dokumente (PDF)'
sortOrder: 16
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: 'https://cdn2.assets-servd.host/'
