fieldLayouts:
  528a51eb-0387-4323-a0e6-0d02c62394b9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: homepage
hasUrls: true
name: Startseite
settings:
  path: '@webroot/assets/images/content/homepage/'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@web/assets/images/content/homepage/'
