fieldLayouts:
  42004d20-3588-4054-924d-d8c468d76a7d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
fs: magazin
handle: magazin
hasUrls: true
name: Magazin
sortOrder: 14
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: 'https://cdn2.assets-servd.host/'
