fieldLayouts:
  9474a1f9-8926-4142-a898-3be63f80a5b9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: mapIcons
hasUrls: true
name: 'Karten- Icons'
settings:
  cdnUrlPattern: ''
  customSubfolder: /assets/images/content/producers/mapicons
  makeUploadsPublic: true
  optimisePrefix: ''
  optimiseUrlPattern: ''
  projectSlug: ''
  securityKey: ''
sortOrder: 18
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: servd\AssetStorage\Volume
url: 'https://cdn2.assets-servd.host/'
