fieldLayouts:
  675f7fbb-24f3-4ef0-b077-3e5e73233093:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: mapThumbnail
hasUrls: true
name: 'Karten Vorschaubilder'
settings:
  cdnUrlPattern: ''
  customSubfolder: /assets/images/content/mapthumbnails/
  makeUploadsPublic: true
  optimisePrefix: ''
  optimiseUrlPattern: ''
  projectSlug: ''
  securityKey: ''
  subfolder: terra-verde/development/assets/images/content/mapthumbnails/
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: servd\AssetStorage\Volume
url: 'https://cdn2.assets-servd.host/'
