fieldLayouts:
  44660dab-9b85-4128-9629-8cf0cfc0eae1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: news
hasUrls: true
name: Aktuelles
settings:
  cdnUrlPattern: ''
  customSubfolder: /assets/images/content/content/news
  makeUploadsPublic: true
  optimisePrefix: ''
  optimiseUrlPattern: ''
  projectSlug: ''
  securityKey: ''
  subfolder: terra-verde/development/assets/images/content/content/news/
sortOrder: 13
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: servd\AssetStorage\Volume
url: 'https://cdn2.assets-servd.host/'
