fieldLayouts:
  fba4c4da-9986-4c2d-bd15-053bc6142513:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: c8246e09-6dc5-4d7c-91e5-e4ad36778317 # OptimizedImages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: productImageWineItaly
hasUrls: true
name: 'Weine Italien'
settings:
  path: '@webroot/assets/images/content/products/wine/italy'
sortOrder: 8
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@web/assets/images/content/products/wine/italy'
