fieldLayouts:
  fe14bedb-d570-4f6a-9bec-9d5d6af7a9ad:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: productImageWineSpain
hasUrls: true
name: 'Weine Spanien'
settings:
  cdnUrlPattern: ''
  customSubfolder: /assets/images/content/products/wine/spain
  makeUploadsPublic: true
  optimisePrefix: ''
  optimiseUrlPattern: ''
  projectSlug: ''
  securityKey: ''
  subfolder: terra-verde/development/assets/images/content/products/wine/spain/
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: servd\AssetStorage\Volume
url: 'https://cdn2.assets-servd.host/'
