fieldLayouts:
  170a9e05-6bb4-4152-9996-5ce1226def46:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
fs: recipes
handle: recipes
hasUrls: true
name: Rezepte
sortOrder: 12
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: 'https://cdn2.assets-servd.host/'
