fieldLayouts:
  b06b9590-a407-4d37-b042-df45767349ba:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: video
handle: video
hasUrls: true
name: Video
sortOrder: 17
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: 'https://cdn2.assets-servd.host/'
