columnSuffix: null
contentColumnType: string
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: accordionInitialState
instructions: ''
name: 'Akkordeon Zustand'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - geschlossen
        -
          - value
          - closed
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - offen
        -
          - value
          - opened
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
