columnSuffix: null
contentColumnType: string
fieldGroup: f80417a4-4032-4133-b6b3-695f48119fa2 # Map
handle: adressMap
instructions: ''
name: 'Adresse Karte'
searchable: true
settings:
  coordinatesDefault:
    __assoc__:
      -
        - lat
        - '47.3833835'
      -
        - lng
        - '8.4862362'
      -
        - zoom
        - '10'
  coordinatesMode: readOnly
  dragPinDefault: null
  dragPinLatitude: null
  dragPinLongitude: null
  dragPinZoom: null
  layout: null
  mapOnSearch: open
  mapOnStart: close
  showMap: false
  subfieldConfig:
    __assoc__:
      -
        - street1
        -
          __assoc__:
            -
              - label
              - 'Street Address'
            -
              - width
              - '100'
            -
              - enabled
              - '1'
            -
              - position
              - '1'
      -
        - street2
        -
          __assoc__:
            -
              - label
              - 'Apartment or Suite'
            -
              - width
              - '100'
            -
              - position
              - '2'
      -
        - city
        -
          __assoc__:
            -
              - label
              - City
            -
              - width
              - '50'
            -
              - enabled
              - '1'
            -
              - position
              - '3'
      -
        - state
        -
          __assoc__:
            -
              - label
              - State
            -
              - width
              - '15'
            -
              - position
              - '4'
      -
        - zip
        -
          __assoc__:
            -
              - label
              - 'Zip Code'
            -
              - width
              - '50'
            -
              - enabled
              - '1'
            -
              - position
              - '5'
      -
        - country
        -
          __assoc__:
            -
              - label
              - Country
            -
              - width
              - '100'
            -
              - position
              - '6'
  visibilityToggle: both
translationKeyFormat: null
translationMethod: none
type: doublesecretagency\googlemaps\fields\AddressField
