columnSuffix: null
contentColumnType: string
fieldGroup: f80417a4-4032-4133-b6b3-695f48119fa2 # Map
handle: adressMap
instructions: ''
name: 'Adresse Karte'
searchable: true
settings:
  errorMessage: 'Unable to find component class ''doublesecretagency\googlemaps\fields\AddressField''.'
  expectedType: doublesecretagency\googlemaps\fields\AddressField
  settings: '{"coordinatesDefault":{"lat":"47.3833835","lng":"8.4862362","zoom":"10"},"coordinatesMode":"readOnly","mapOnSearch":"open","mapOnStart":"close","showMap":false,"subfieldConfig":{"street1":{"label":"Street Address","width":"100","enabled":"1","position":"1"},"street2":{"label":"Apartment or Suite","width":"100","position":"2"},"city":{"label":"City","width":"50","enabled":"1","position":"3"},"state":{"label":"State","width":"15","position":"4"},"zip":{"label":"Zip Code","width":"50","enabled":"1","position":"5"},"country":{"label":"Country","width":"100","position":"6"}},"visibilityToggle":"both"}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
