columnSuffix: null
contentColumnType: string
fieldGroup: bcc2f7c9-e4b5-432b-b079-3cd963db5854 # Produzenten
handle: articleTypeMan
instructions: ''
name: Artikeltyp
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:08ff3872-a05e-4722-868b-6bbe52bad972' # Produzenten
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
