columnSuffix: null
contentColumnType: string
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: articleImage
instructions: ''
name: 'Produkt Bild'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:63339d3e-c6d1-4455-be6d-33715340baf0' # Produkte
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:63339d3e-c6d1-4455-be6d-33715340baf0' # Produkte
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:63339d3e-c6d1-4455-be6d-33715340baf0' # Produkte
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
