columnSuffix: null
contentColumnType: text
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: articleArticleGroup
instructions: ''
name: Artikelgruppe
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
