columnSuffix: null
contentColumnType: string
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: articleCategoriesGift
instructions: ''
name: 'Kategorien (Geschenke)'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:00a72f8a-e7ae-4303-bcc0-e693888454a0' # Geschenke
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
