columnSuffix: ocwzdgrr
contentColumnType: string(7)
fieldGroup: 99dbe745-472a-4403-8fbe-15424920fb29 # Newsletter
handle: backgroundColorHeadingNewsletter
instructions: ''
name: Hintergrundfarbe
searchable: false
settings:
  defaultColor: '#ffffff'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
