columnSuffix: tsnshhsh
contentColumnType: string
fieldGroup: bcc2f7c9-e4b5-432b-b079-3cd963db5854 # Produzenten
handle: boxAlign
instructions: ''
name: 'Box Positionierung'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - grid-shift__left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Mitte
        -
          - value
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Rechts
        -
          - value
          - grid-shift__right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
