columnSuffix: null
contentColumnType: string
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: buttonLinkColor
instructions: ''
name: 'Link Farbe'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - blau
        -
          - value
          - blue
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - weiss
        -
          - value
          - white
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
