columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 1856a1a8-498c-4498-84ad-6fcbe1de89f7 # Kategorien
handle: catNumber
instructions: ''
name: Nummer
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
