columnSuffix: null
contentColumnType: string
fieldGroup: 57003c64-aadc-404d-a990-553d81d5fef3 # Startseite
handle: contentElementsHomepage
instructions: ''
name: 'Inhaltselemente Startseite'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentelementshomepage}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
