columnSuffix: null
contentColumnType: string
fieldGroup: 99dbe745-472a-4403-8fbe-15424920fb29 # Newsletter
handle: contentElementsNewsletter
instructions: ''
name: Inhaltselemente
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentelementsnewsletter}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
