columnSuffix: null
contentColumnType: string
fieldGroup: 57003c64-aadc-404d-a990-553d81d5fef3 # Startseite
handle: contentElementsStartpage
instructions: ''
name: 'Inhaltselemente Startseite'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
