columnSuffix: null
contentColumnType: string
fieldGroup: 546e63c7-3ad2-424d-ad71-31f33a561a7f # Kontakt | Globals
handle: emailTwo
instructions: ''
name: 'Email 2'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
