contentColumnType: string
fieldGroup: 546e63c7-3ad2-424d-ad71-31f33a561a7f
handle: emailOne
instructions: ''
name: 'Email 1'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
