columnSuffix: qfghrunv
contentColumnType: string
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: externerLinkPreview
instructions: ''
name: 'Externer Link (Preview'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''prismaticbytes\prismaticlinks\fields\PrismaticLinksField''.'
  expectedType: prismaticbytes\prismaticlinks\fields\PrismaticLinksField
  settings: '{"someAttribute":"Some Default"}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
