columnSuffix: null
contentColumnType: text
fieldGroup: 57003c64-aadc-404d-a990-553d81d5fef3 # Startseite
handle: homepage
instructions: ''
name: Startseite
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
