columnSuffix: null
contentColumnType: string
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: image
instructions: ''
name: Bild
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:789fdb6d-520f-4cf1-be1e-478056358e79' # Inhaltsbilder
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:63339d3e-c6d1-4455-be6d-33715340baf0' # Produkte
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:789fdb6d-520f-4cf1-be1e-478056358e79' # Inhaltsbilder
    - 'volume:63339d3e-c6d1-4455-be6d-33715340baf0' # Produkte
    - 'volume:e221908a-3496-4eb9-8727-682969a83304' # Startseite
    - 'volume:3bb39d28-0fde-4351-82f7-4a35d96e4a3b' # Karten Vorschaubilder
    - 'volume:127bba7e-6a96-4ffa-8cbb-f4c17d39e347' # Team
    - 'volume:62aa7cc1-c9ad-4ef4-9d94-4fc3275ba26a' # Produzenten
    - 'volume:b32fd57a-109a-4013-bf90-72b25ad6b6cd' # Weine Spanien
    - 'volume:a67b61db-e6cc-4102-85f1-473d36f52ea8' # Weine Italien
    - 'volume:8aec977e-df97-4119-93e9-0b745252a944' # Weine Frankreich
    - 'volume:cfba8ac8-e0a0-405f-87ed-accd8f27b372' # Geschenksets
    - 'volume:1d881bde-d2bf-408a-9434-f2f08b65cff8' # Dokumente
    - 'volume:e61fb032-eec0-4f11-b450-86d1adea8934' # Rezepte
    - 'volume:39720a7b-fb62-4919-8f8c-b57fe485a7a6' # Aktuelles
    - 'volume:57d4d8f2-0e49-45bf-9f84-2e1917ef7c02' # Magazin
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
