columnSuffix: ijwtpocl
contentColumnType: string(7)
fieldGroup: bcc2f7c9-e4b5-432b-b079-3cd963db5854 # Produzenten
handle: infoboxBgColor
instructions: ''
name: 'Infobox Hintergrundfarbe'
searchable: false
settings:
  defaultColor: '#f7f5f0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
