columnSuffix: gfxtliwu
contentColumnType: text
fieldGroup: bcc2f7c9-e4b5-432b-b079-3cd963db5854 # Produzenten
handle: linkTextDetailPage
instructions: 'Wie soll der Link zur Detailseiten heissen?'
name: Linktext
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
