columnSuffix: yafvxodq
contentColumnType: text
fieldGroup: 99dbe745-472a-4403-8fbe-15424920fb29 # Newsletter
handle: newsletterSalutation
instructions: "Wird nur angezeigt, wenn oben \"Ja\" ausgewählt ist. \r\nz.B. \"Hallo ...\" oder \"Guten Tag ...\", danach wird automatisch der volle Name eingesetzt, so wie bei der Anmeldung gespeichert. "
name: Anrede
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
