contentColumnType: text
fieldGroup: 546e63c7-3ad2-424d-ad71-31f33a561a7f
handle: openingHoursOne
instructions: ''
name: Öffnungszeiten
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
