columnSuffix: uxiqkwwy
contentColumnType: text
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: orderNotes
instructions: ''
name: Notiz
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
