columnSuffix: gzrfgcwj
contentColumnType: integer(10)
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: outOfStock
instructions: ''
name: 'Out of Stock'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
