columnSuffix: null
contentColumnType: 'decimal(12,2)'
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: priceRetailTrader
instructions: ''
name: 'Preise (Detailhandel)'
searchable: false
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
