contentColumnType: string
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: productDescription
instructions: ''
name: 'Produkt Beschreibung'
searchable: false
settings:
  contentTable: '{{%matrixcontent_productdescription}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
