columnSuffix: twddjwwy
contentColumnType: text
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: recipes
instructions: ''
name: Rezepte
searchable: true
settings:
  assetSources:
    - 'folder:ea4c3670-a713-4af4-a4a4-3fc935c21a56'
translationKeyFormat: null
translationMethod: none
type: nystudio107\recipe\fields\Recipe
