columnSuffix: twddjwwy
contentColumnType: text
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: recipes
instructions: ''
name: Rezepte
searchable: true
settings:
  assetSources:
    - 'folder:f54eed2a-4ea3-4448-9b61-1708ad15d18d'
    - 'folder:32fccaea-9c9a-40da-8619-dc240df30cd6'
    - 'folder:31db02d5-bba7-4a06-8bb9-5bdf3a53c879'
    - 'folder:4b43b7c1-a9df-4549-90e7-0fb32784f10f'
translationKeyFormat: null
translationMethod: none
type: nystudio107\recipe\fields\Recipe
