columnSuffix: twddjwwy
contentColumnType: text
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: recipes
instructions: ''
name: Rezepte
searchable: true
settings:
  assetSources:
    - 'folder:962e6c44-86b9-4a77-bf39-8a362ee99399'
translationKeyFormat: null
translationMethod: none
type: nystudio107\recipe\fields\Recipe
