columnSuffix: null
contentColumnType: string
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: relationsManufactors
instructions: ''
name: 'Relations Hersteller'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''Page8\ManyToMany\fields\ManyToManyField''.'
  expectedType: Page8\ManyToMany\fields\ManyToManyField
  settings: '{"singleField":"131","source":{"value":"5","type":"section"}}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
