columnSuffix: bvmunkua
contentColumnType: text
fieldGroup: 9ebc7c8b-c103-4448-b46f-2b29f154a805 # SEO
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - siteNamePosition
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
    - sitemapFiles
    - sitemapAltLinks
    - sitemapChangeFreq
    - sitemapPriority
  sitemapTabEnabled: '1'
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
