columnSuffix: ettqnkfd
contentColumnType: text
fieldGroup: 9ebc7c8b-c103-4448-b46f-2b29f154a805 # SEO
handle: seoSettings
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - mainEntityOfPage
    - seoTitle
    - siteNamePosition
    - seoDescription
    - seoKeywords
    - seoImage
    - seoImageTransform
    - seoImageDescription
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
