columnSuffix: null
contentColumnType: string
fieldGroup: 8e1d4181-5012-4bbc-9a55-048bb89f0863 # Super Filter
handle: superFilterShowTypes
instructions: null
name: 'Show Types'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Films
        -
          - value
          - films
    -
      __assoc__:
        -
          - optgroup
          - Series
    -
      __assoc__:
        -
          - label
          - 'TV Series'
        -
          - value
          - tv-series
    -
      __assoc__:
        -
          - label
          - Documentaries
        -
          - value
          - documentaries
    -
      __assoc__:
        -
          - label
          - Anime
        -
          - value
          - anime
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
