columnSuffix: grfgejba
contentColumnType: string
fieldGroup: 4fe8dfc1-b512-4508-a756-d29539b14b62 # Artikel
handle: userAddressAlternativePhoneNew
instructions: null
name: 'Alternative Phone'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
