columnSuffix: null
contentColumnType: boolean
fieldGroup: 84b58543-313b-40d6-a50b-2fbf9262c271 # Benutzer
handle: userAGBCheck
instructions: ''
name: AGB
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
