columnSuffix: null
contentColumnType: text
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: youtubeVideoSrc
instructions: 'Auf Youtube gehen und Video öffnen. Unterhalb Video auf "Teilen" klicken und im Dialog oben "Einbetten" wählen. Die "src" aus dem Code-Beispiel kopieren (z.B. https://www.youtube.com/watch?v=h1P-BMedCVg) und hier einfügen.'
name: 'Youtube Video Src'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
