columnSuffix: null
contentColumnType: string
fieldGroup: d5eb7b01-8b1f-4b3f-83c7-ccfa4c76d49d # Inhaltselemente
handle: youtubeMatrixVideoList
instructions: ''
name: 'Youtube Video Liste'
searchable: false
settings:
  contentTable: '{{%matrixcontent_youtubematrixvideolist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
