fieldLayouts:
  0eee14fb-4fea-4007-8011-22d7113e5183:
    tabs:
      -
        elements:
          -
            fieldUid: 4fbda939-0a27-483c-a7c8-7def0a9418ee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: a6d404c5-d5dc-4ac6-846b-d068efafba1a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ab11f679-477b-4903-9086-d00fb5489f93
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 2a604d11-f35a-4546-a33a-b2465e0017a9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: af1c566f-cdf2-4ae1-a225-934165929d1a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 673dbddb-972b-44b7-b50c-ac5b649321ab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 023a6dc1-c7ac-4b4a-9908-220b69485841
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Kontakt
        sortOrder: 1
handle: footerGlobal
name: Footer
