fieldLayouts:
  b3da1473-819d-48f5-97e0-2a6c6cea7a30:
    tabs:
      -
        elements:
          -
            fieldUid: 57e5fec1-460f-4063-a3db-815af978dc8f # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ad28cff2-9b0f-4a4d-b9b7-09e42104fc9d # Logo - Bio Störer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Generic
        sortOrder: 1
handle: generic
name: Generic
sortOrder: 4
