fieldLayouts:
  66ac0194-0c31-4a2f-b346-38489e61fe51:
    tabs:
      -
        elements:
          -
            fieldUid: 86598fdd-8228-49e1-88da-4744029bfcef # Prdoukte Sortieren
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Custom Listing'
        sortOrder: 1
handle: storeCustomization
name: 'Shop Anpassungen'
sortOrder: 3
