defaultPlacement: end
enableVersioning: true
handle: aboutUsStructure
name: 'Über uns'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    enabledByDefault: true
    hasUrls: true
    template: _pages/ueberuns/index
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: d653b475-c150-4f4d-b997-434bf30ca07d
type: structure
