defaultPlacement: end
enableVersioning: true
handle: blogCategories
name: 'Blog Kategorien'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog/categories/_entry.twig
    uriFormat: 'blog/{slug}'
structure:
  maxLevels: null
  uid: 8a00270f-0535-41de-a01c-ae51de0fbd60
type: structure
