defaultPlacement: end
enableVersioning: true
handle: producersStructure
name: Produzenten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    enabledByDefault: true
    hasUrls: true
    template: _pages/produkte/produzenten/entry
    uriFormat: 'produzenten/{slug}'
structure:
  maxLevels: null
  uid: 4e635185-aa03-49cf-8339-b484639985a5
type: structure
