defaultPlacement: end
enableVersioning: true
handle: productStructure
name: Produkte
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147: # Terra Verde
    enabledByDefault: true
    hasUrls: true
    template: _pages/produkte/index
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 1c54cf34-7687-4e38-b651-a0f332dfed05
type: structure
