enableVersioning: true
handle: retailTradeStructure
name: Detailhandel
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dd0cd05e-0cb9-4a76-b993-3cb70e6fc147:
    enabledByDefault: true
    hasUrls: true
    template: _pages/detailhandel/index
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 04da9a53-ea32-4479-889c-f76650bcb57e
type: structure
