tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\commerce\fieldlayoutelements\UserAddressSettings
        uid: 869fdf5f-1c4e-448c-83d7-40006b6dac22
        userCondition: null
        warning: null
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 622c7c21-446f-473b-a0f5-7248df3170e7
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: e73cef0c-3dda-42d1-9640-bb88eed4bf51
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 237386f1-f7ff-4aea-90aa-6fbd0bd925a1
        userCondition: null
        warning: null
      -
        elementCondition: null
        fieldUid: cf6d2e14-00af-47af-999a-9b5aee73a1df
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 76d9089b-b24e-4cc8-ab46-00153fc7efe8
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\FullNameField
        uid: dd365064-adac-42dd-8852-2ae57b39be18
        userCondition: null
        warning: null
        width: 100
      -
        attribute: organization
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\OrganizationField
        uid: 8c3986e8-0681-4281-bc9f-045a87b390d9
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 435d5797-f856-4521-bc23-a57e3a09b552 # Phone Number
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 98855725-6cd1-47cb-869f-1d4d40411f2c
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 40de0ae9-aa16-4969-beb2-ad8dae160183 # Notes
        instructions: null
        label: Notiz
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4587a819-dc06-409a-b5f7-945f0383a79b
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: 09a8bdad-9757-41b2-8e59-acd2a2385597
    userCondition: null
